# Model
model_name: "/home/zzh/code/TTS/Orpheus-TTS/pretrained_models/meta-llama/Llama-3.2-3B-Instruct"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "/home/zzh/code/TTS/Orpheus-TTS/pretrained_models/meta-llama/Llama-3.2-3B-Instruct"


# Training Args
epochs: 1
batch_size: 8
number_processes: 8
pad_token: 128263
save_steps: 1000
learning_rate: 5.0e-5
ratio: 0.5

# Datasets
text_QA_dataset: /home/zzh/code/TTS/Orpheus-TTS/data/processed/text/data-00000-of-00001_pretrain.parquet
TTS_dataset: /home/zzh/code/TTS/Orpheus-TTS/data/processed/yuanshen/data-00000-of-00001_pretrain.parquet

# Naming and paths
save_folder: "ckpt"
project_name: "pretrain-orpheus"
run_name: "pretrain-orpheus"
